// Generated by scripts/build-data.py. Do not edit by hand.
const CHAI_DATA = {
 "vocab": [
  {
   "id": "w0",
   "phonetic": "salām",
   "english": "hello",
   "script": "سَلام",
   "lesson": 1
  },
  {
   "id": "w1",
   "phonetic": "chetor-ee?",
   "english": "how are you?",
   "script": "چِطوری؟",
   "lesson": 1
  },
  {
   "id": "w2",
   "phonetic": "khoob-am",
   "english": "I’m well",
   "script": "خوبَم",
   "lesson": 1
  },
  {
   "id": "w3",
   "phonetic": "merci",
   "english": "thank you",
   "script": "مِرسی",
   "lesson": 1
  },
  {
   "id": "w4",
   "phonetic": "khaylee",
   "english": "very",
   "script": "خِیلی",
   "lesson": 1
  },
  {
   "id": "w5",
   "phonetic": "khaylee khoob-am",
   "english": "I’m very well",
   "script": "خِیلی خوبَم",
   "lesson": 1
  },
  {
   "id": "w6",
   "phonetic": "khoob neestam",
   "english": "I’m not well",
   "script": "خوب نیستَم",
   "lesson": 1
  },
  {
   "id": "w7",
   "phonetic": "man",
   "english": "me / I",
   "script": "مَن",
   "lesson": 1
  },
  {
   "id": "w8",
   "phonetic": "bad neestam",
   "english": "I’m not bad",
   "script": "بَد نیستَم",
   "lesson": 1
  },
  {
   "id": "w9",
   "phonetic": "ālee",
   "english": "great",
   "script": "عالی",
   "lesson": 1
  },
  {
   "id": "w10",
   "phonetic": "chetor-een?",
   "english": "how are you? (formal)",
   "script": "چِطُورین؟",
   "lesson": 1
  },
  {
   "id": "w11",
   "phonetic": "hālé shomā chetor-é?",
   "english": "how are you? (formal)",
   "script": "حالِ شُما چِطورِه؟",
   "lesson": 1
  },
  {
   "id": "w12",
   "phonetic": "hālet chetor-é?",
   "english": "how are you? (informal)",
   "script": "حالِت چِطورِه؟",
   "lesson": 1
  },
  {
   "id": "w13",
   "phonetic": "khoob-ee?",
   "english": "are you well? (informal)",
   "script": "خوبی؟",
   "lesson": 1
  },
  {
   "id": "w14",
   "phonetic": "mamnoon-am",
   "english": "thank you",
   "script": "مَمنونَم",
   "lesson": 1
  },
  {
   "id": "w15",
   "phonetic": "chetor peesh meeré?",
   "english": "how’s it going?",
   "script": "چِطُور پیش می‌رِه؟",
   "lesson": 1
  },
  {
   "id": "w16",
   "phonetic": "ché khabar?",
   "english": "what’s the news? (what’s up?)",
   "script": "چِه خَبَر؟",
   "lesson": 1
  },
  {
   "id": "w17",
   "phonetic": "sobh bekhayr",
   "english": "good morning",
   "script": "صُبح بِخِیر",
   "lesson": 2
  },
  {
   "id": "w18",
   "phonetic": "rooz bekhayr",
   "english": "good day",
   "script": "روز بِخِیر",
   "lesson": 2
  },
  {
   "id": "w19",
   "phonetic": "asr bekhayr",
   "english": "good afternoon",
   "script": "عَصر بِخِیر",
   "lesson": 2
  },
  {
   "id": "w20",
   "phonetic": "shab bekhayr",
   "english": "good night",
   "script": "شَب بِخِیر",
   "lesson": 2
  },
  {
   "id": "w21",
   "phonetic": "khodāhāfez",
   "english": "goodbye",
   "script": "خُداحافِظ",
   "lesson": 2
  },
  {
   "id": "w22",
   "phonetic": "fe’lan",
   "english": "goodbye (for now)",
   "script": "فِعلاً",
   "lesson": 2
  },
  {
   "id": "w23",
   "phonetic": "bé omeedé deedār",
   "english": "in hopes of seeing you again",
   "script": "بِه اُمیدِ دیدار",
   "lesson": 2
  },
  {
   "id": "w24",
   "phonetic": "tā ba’d",
   "english": "until later",
   "script": "تا بَعد",
   "lesson": 2
  },
  {
   "id": "w25",
   "phonetic": "tā fardā",
   "english": "until tomorrow",
   "script": "تا فَردا",
   "lesson": 2
  },
  {
   "id": "w26",
   "phonetic": "esmé man ____ hast",
   "english": "my name is ____",
   "script": "اِسمِ مَن ــــــــ هَست",
   "lesson": 2
  },
  {
   "id": "w27",
   "phonetic": "khoshvaghtam",
   "english": "pleased to meet you",
   "script": "خوشوَقتَم",
   "lesson": 2
  },
  {
   "id": "w28",
   "phonetic": "ghorbānat",
   "english": "kind of you, your sacrifice",
   "script": "قُربانَت",
   "lesson": 2
  },
  {
   "id": "w29",
   "phonetic": "dorood!",
   "english": "hi! greetings!",
   "script": "دُرود",
   "lesson": 2
  },
  {
   "id": "w30",
   "phonetic": "safar bekhayr",
   "english": "safe journey (bon voyage!)",
   "script": "سَفَر بِخِیر",
   "lesson": 2
  },
  {
   "id": "w31",
   "phonetic": "khodā negahdār",
   "english": "goodbye (God keep you safe)",
   "script": "خُدا نِگَهدار",
   "lesson": 2
  },
  {
   "id": "w32",
   "phonetic": "meebeenamet",
   "english": "see you (informal, addressed to one person)",
   "script": "می‌بینَمِت",
   "lesson": 2
  },
  {
   "id": "w33",
   "phonetic": "shomā",
   "english": "you (formal)",
   "script": "شُما",
   "lesson": 3
  },
  {
   "id": "w34",
   "phonetic": "tō",
   "english": "you (informal)",
   "script": "تُو",
   "lesson": 3
  },
  {
   "id": "w35",
   "phonetic": "esmé tō chee-yé?",
   "english": "what is your name? (informal)",
   "script": "اِسمِ تُو چیِه؟",
   "lesson": 3
  },
  {
   "id": "w36",
   "phonetic": "esmé shomā chee-yé?",
   "english": "what is your name? (formal)",
   "script": "اِسمِ شُما چیِه؟",
   "lesson": 3
  },
  {
   "id": "w37",
   "phonetic": "tō ahlé kojā hastee?",
   "english": "where are you from? (informal)",
   "script": "تُو اَهلِ کُجا هَستی؟",
   "lesson": 3
  },
  {
   "id": "w38",
   "phonetic": "shomā ahlé kojā hasteen?",
   "english": "where are you from? (formal)",
   "script": "شُما اَهلِ کُجا هَستین؟",
   "lesson": 3
  },
  {
   "id": "w39",
   "phonetic": "man az ____ hastam",
   "english": "I am from ____",
   "script": "مَن اَز ــــــــــــــــــ هَستَم",
   "lesson": 3
  },
  {
   "id": "w40",
   "phonetic": "man az eerān hastam",
   "english": "I am from Iran",
   "script": "مَن اَز ایران هَستَم",
   "lesson": 3
  },
  {
   "id": "w41",
   "phonetic": "āmreekā",
   "english": "the United States",
   "script": "آمریکا",
   "lesson": 3
  },
  {
   "id": "w42",
   "phonetic": "espāniā",
   "english": "Spain",
   "script": "اِسپانیا",
   "lesson": 3
  },
  {
   "id": "w43",
   "phonetic": "englees",
   "english": "England",
   "script": "اِنگلیس",
   "lesson": 3
  },
  {
   "id": "w44",
   "phonetic": "ālmān",
   "english": "Germany",
   "script": "آلمان",
   "lesson": 3
  },
  {
   "id": "w45",
   "phonetic": "farāncé",
   "english": "France",
   "script": "فَرانسِه",
   "lesson": 3
  },
  {
   "id": "w46",
   "phonetic": "mekseek",
   "english": "Mexico",
   "script": "مِکزیک",
   "lesson": 3
  },
  {
   "id": "w47",
   "phonetic": "ham",
   "english": "also",
   "script": "هَم",
   "lesson": 3
  },
  {
   "id": "w48",
   "phonetic": "man az tehrān hastam",
   "english": "I am from Tehran",
   "script": "مَن اَز تِهران هَستَم",
   "lesson": 3
  },
  {
   "id": "w49",
   "phonetic": "kānādā",
   "english": "Canada",
   "script": "کانادا",
   "lesson": 3
  },
  {
   "id": "w50",
   "phonetic": "otreesh",
   "english": "Austria",
   "script": "اُتریش",
   "lesson": 3
  },
  {
   "id": "w51",
   "phonetic": "jāpon",
   "english": "Japan",
   "script": "ژاپُن",
   "lesson": 3
  },
  {
   "id": "w52",
   "phonetic": "eetāleeā",
   "english": "Italy",
   "script": "ایتالیا",
   "lesson": 3
  },
  {
   "id": "w53",
   "phonetic": "cheen",
   "english": "China",
   "script": "چین",
   "lesson": 3
  },
  {
   "id": "w54",
   "phonetic": "hendoostān",
   "english": "India",
   "script": "هِندوستان",
   "lesson": 3
  },
  {
   "id": "w55",
   "phonetic": "tō az teksās hastee?",
   "english": "are you from Texas? (informal)",
   "script": "تُو اَز تِکزاس هَستی؟",
   "lesson": 4
  },
  {
   "id": "w56",
   "phonetic": "shomā az teksās hasteen?",
   "english": "are you from Texas? (formal)",
   "script": "شُما اَز تِکزاس هَستین؟",
   "lesson": 4
  },
  {
   "id": "w57",
   "phonetic": "balé",
   "english": "yes",
   "script": "بَلِه",
   "lesson": 4
  },
  {
   "id": "w58",
   "phonetic": "āré",
   "english": "yeah",
   "script": "آرِه",
   "lesson": 4
  },
  {
   "id": "w59",
   "phonetic": "na",
   "english": "no",
   "script": "نَه",
   "lesson": 4
  },
  {
   "id": "w60",
   "phonetic": "man az ______ hastam",
   "english": "I am from ______",
   "script": "مَن اَز ـــــــــــــــ هَستَم",
   "lesson": 4
  },
  {
   "id": "w61",
   "phonetic": "man az ______ neestam",
   "english": "I am not from ______",
   "script": "مَن اَز ـــــــــــــــ نیستَم",
   "lesson": 4
  },
  {
   "id": "w62",
   "phonetic": "man leylā hastam",
   "english": "I am Leyla",
   "script": "مَن لِیلا هَستَم",
   "lesson": 4
  },
  {
   "id": "w63",
   "phonetic": "man dar ___ zendegee meekonam",
   "english": "I live in ___",
   "script": "مَن دَر ـــــــــــــــ زِندِگی می‌کُنَم",
   "lesson": 4
  },
  {
   "id": "w64",
   "phonetic": "dar ____ zendegee meekonam",
   "english": "I live in _____",
   "script": "دَر ـــــــــــــــ زِندِگی می‌کُنَم",
   "lesson": 4
  },
  {
   "id": "w65",
   "phonetic": "tō kojā zendegee meekonee?",
   "english": "where do you live? (informal)",
   "script": "تُو کُجا زِندِگی می‌کُنی؟",
   "lesson": 4
  },
  {
   "id": "w66",
   "phonetic": "shomā kojā zendegee meekoneen?",
   "english": "where do you live? (formal)",
   "script": "شُما کُجا زِندِگی می‌کُنین؟",
   "lesson": 4
  },
  {
   "id": "w67",
   "phonetic": "kojā zendegee meekonee?",
   "english": "where do you live? (informal)",
   "script": "کُجا زِندِگی می‌کُنی؟",
   "lesson": 4
  },
  {
   "id": "w68",
   "phonetic": "kojā zendegee meekoneen?",
   "english": "where do you live? (formal)",
   "script": "کُجا زِندِگی می‌‌کُنین؟",
   "lesson": 4
  },
  {
   "id": "w69",
   "phonetic": "man az ____ hastam, valee hālā dar ____ zendegee meekonam",
   "english": "I am from ____, but now I live in ____",
   "script": "مَن اَز ـــــــــــ هَستَم، وَلی حالا دَر ـــــــــــ زِندِگی می‌کُنَم",
   "lesson": 4
  },
  {
   "id": "w70",
   "phonetic": "valee",
   "english": "but",
   "script": "وَلی",
   "lesson": 4
  },
  {
   "id": "w71",
   "phonetic": "hālā",
   "english": "now",
   "script": "حالا",
   "lesson": 4
  },
  {
   "id": "w72",
   "phonetic": "eenjā",
   "english": "here",
   "script": "اینجا",
   "lesson": 4
  },
  {
   "id": "w73",
   "phonetic": "az eenjā hastee?",
   "english": "are you from here? (informal)",
   "script": "اَز اینجا هَستی؟",
   "lesson": 4
  },
  {
   "id": "w74",
   "phonetic": "az eenjā hasteen?",
   "english": "are you from here? (formal)",
   "script": "اَز اینجا هَستین؟",
   "lesson": 4
  },
  {
   "id": "w75",
   "phonetic": "az eenjā neestam",
   "english": "I am not from here",
   "script": "اَز اینجا نیستَم",
   "lesson": 4
  },
  {
   "id": "w76",
   "phonetic": "az eenjā hastam",
   "english": "I am from here",
   "script": "اَز اینجا هَستَم",
   "lesson": 4
  },
  {
   "id": "w77",
   "phonetic": "esmesh ____ hast",
   "english": "its name is ____",
   "script": "اِسمِش ــــــــــــ هَست",
   "lesson": 4
  },
  {
   "id": "w78",
   "phonetic": "ahsant",
   "english": "excellent, well done",
   "script": "اَحسَنت",
   "lesson": 4
  },
  {
   "id": "w79",
   "phonetic": "barādar",
   "english": "brother",
   "script": "بَرادَر",
   "lesson": 5
  },
  {
   "id": "w80",
   "phonetic": "khāhar",
   "english": "sister",
   "script": "خواهَر",
   "lesson": 5
  },
  {
   "id": "w81",
   "phonetic": "mādar",
   "english": "mother",
   "script": "مادَر",
   "lesson": 5
  },
  {
   "id": "w82",
   "phonetic": "pedar",
   "english": "father",
   "script": "پِدَر",
   "lesson": 5
  },
  {
   "id": "w83",
   "phonetic": "dokhtar",
   "english": "daughter (literally 'girl')",
   "script": "دُختَر",
   "lesson": 5
  },
  {
   "id": "w84",
   "phonetic": "pesar",
   "english": "son (literally 'boy')",
   "script": "پِسَر",
   "lesson": 5
  },
  {
   "id": "w85",
   "phonetic": "shohar",
   "english": "husband",
   "script": "شُوهَر",
   "lesson": 5
  },
  {
   "id": "w86",
   "phonetic": "zan",
   "english": "wife (literally 'woman')",
   "script": "زَن",
   "lesson": 5
  },
  {
   "id": "w87",
   "phonetic": "mādaré man",
   "english": "my mother",
   "script": "مادَرِ مَن",
   "lesson": 5
  },
  {
   "id": "w88",
   "phonetic": "pesaré man",
   "english": "my son",
   "script": "پِسَرِ مَن",
   "lesson": 5
  },
  {
   "id": "w89",
   "phonetic": "dokhtaré man",
   "english": "my daughter",
   "script": "دُختَرِ مَن",
   "lesson": 5
  },
  {
   "id": "w90",
   "phonetic": "een ___-é man-é",
   "english": "this is my ___ (informal)",
   "script": "این __________ مَنِه",
   "lesson": 5
  },
  {
   "id": "w91",
   "phonetic": "eeshoon ___-é man-and",
   "english": "this is my ___ (formal)",
   "script": "ایشون __________ مَن‌اَند",
   "lesson": 5
  },
  {
   "id": "w92",
   "phonetic": "esmesh ___-é",
   "english": "his/her name is ___ (informal)",
   "script": "اِسمِش _________-ه",
   "lesson": 5
  },
  {
   "id": "w93",
   "phonetic": "esmeshoon ___-é",
   "english": "his/her name is ____ (formal)",
   "script": "اِسمِشون _________-ه",
   "lesson": 5
  },
  {
   "id": "w94",
   "phonetic": "hamsar",
   "english": "spouse (either wife or husband)",
   "script": "هَمسَر",
   "lesson": 5
  },
  {
   "id": "w95",
   "phonetic": "mādar bozorg",
   "english": "grandmother",
   "script": "مادَربُزُرگ",
   "lesson": 5
  },
  {
   "id": "w96",
   "phonetic": "pedar bozorg",
   "english": "grandfather",
   "script": "پِدَربُزُرگ",
   "lesson": 5
  },
  {
   "id": "w97",
   "phonetic": "khāle",
   "english": "aunt (maternal)",
   "script": "خالِه",
   "lesson": 5
  },
  {
   "id": "w98",
   "phonetic": "dāyee",
   "english": "uncle (maternal)",
   "script": "دايي",
   "lesson": 5
  },
  {
   "id": "w99",
   "phonetic": "amé",
   "english": "aunt (paternal)",
   "script": "عَمِّه",
   "lesson": 5
  },
  {
   "id": "w100",
   "phonetic": "amoo",
   "english": "uncle (paternal)",
   "script": "عَمو",
   "lesson": 5
  },
  {
   "id": "w101",
   "phonetic": "māmān",
   "english": "mom",
   "script": "مامان",
   "lesson": 6
  },
  {
   "id": "w102",
   "phonetic": "bābā",
   "english": "dad",
   "script": "بابا",
   "lesson": 6
  },
  {
   "id": "w103",
   "phonetic": "bābāyé tō",
   "english": "your dad (informal)",
   "script": "بابایِ تُو",
   "lesson": 6
  },
  {
   "id": "w104",
   "phonetic": "dāram",
   "english": "I have",
   "script": "دارَم",
   "lesson": 6
  },
  {
   "id": "w105",
   "phonetic": "yé",
   "english": "a (one)",
   "script": "یِه",
   "lesson": 6
  },
  {
   "id": "w106",
   "phonetic": "yé khāhar",
   "english": "a sister/one sister",
   "script": "یِه خواهَر",
   "lesson": 6
  },
  {
   "id": "w107",
   "phonetic": "yé pesar",
   "english": "a son/one son",
   "script": "یِه پِسَر",
   "lesson": 6
  },
  {
   "id": "w108",
   "phonetic": "man yé khāhar dāram",
   "english": "I have a sister",
   "script": "مَن یِه خواهَر دارَم",
   "lesson": 6
  },
  {
   "id": "w109",
   "phonetic": "yek",
   "english": "1",
   "script": "یِک",
   "lesson": 6
  },
  {
   "id": "w110",
   "phonetic": "dō",
   "english": "2",
   "script": "دُو",
   "lesson": 6
  },
  {
   "id": "w111",
   "phonetic": "sé",
   "english": "3",
   "script": "سِه",
   "lesson": 6
  },
  {
   "id": "w112",
   "phonetic": "chahār",
   "english": "4",
   "script": "چَهار",
   "lesson": 6
  },
  {
   "id": "w113",
   "phonetic": "panj",
   "english": "5",
   "script": "پَنج",
   "lesson": 6
  },
  {
   "id": "w114",
   "phonetic": "sheesh",
   "english": "6",
   "script": "شیش",
   "lesson": 6
  },
  {
   "id": "w115",
   "phonetic": "haft",
   "english": "7",
   "script": "هَفت",
   "lesson": 6
  },
  {
   "id": "w116",
   "phonetic": "hasht",
   "english": "8",
   "script": "هَشت",
   "lesson": 6
  },
  {
   "id": "w117",
   "phonetic": "noh",
   "english": "9",
   "script": "نُه",
   "lesson": 6
  },
  {
   "id": "w118",
   "phonetic": "dah",
   "english": "10",
   "script": "دَه",
   "lesson": 6
  },
  {
   "id": "w119",
   "phonetic": "yek dokhtar",
   "english": "one daughter",
   "script": "یِک دُختَر",
   "lesson": 6
  },
  {
   "id": "w120",
   "phonetic": "dō dokhtar",
   "english": "two daughters",
   "script": "دُو دُختَر",
   "lesson": 6
  },
  {
   "id": "w121",
   "phonetic": "yek barādar",
   "english": "one brother",
   "script": "یِک بَرادَر",
   "lesson": 6
  },
  {
   "id": "w122",
   "phonetic": "dō barādar",
   "english": "two brothers",
   "script": "دُو بَرادَر",
   "lesson": 6
  },
  {
   "id": "w123",
   "phonetic": "yek pesar",
   "english": "one son",
   "script": "یِک پِسَر",
   "lesson": 6
  },
  {
   "id": "w124",
   "phonetic": "dō pesar",
   "english": "two sons",
   "script": "دُو پِسَر",
   "lesson": 6
  },
  {
   "id": "w125",
   "phonetic": "esmāshoon sārā va dārā hast",
   "english": "their names are Sara and Dara",
   "script": "اِسماشون سارا وَ دارا هَست",
   "lesson": 6
  },
  {
   "id": "w126",
   "phonetic": "sefr",
   "english": "zero",
   "script": "صِفر",
   "lesson": 6
  },
  {
   "id": "w127",
   "phonetic": "kee",
   "english": "who",
   "script": "کی",
   "lesson": 6
  },
  {
   "id": "w128",
   "phonetic": "tō dokhtaré man hastee",
   "english": "you are my daughter",
   "script": "تُو دُختَرِ مَن هَستی",
   "lesson": 6
  },
  {
   "id": "w129",
   "phonetic": "(man) mo’alem hastam",
   "english": "I am a teacher",
   "script": "(مَن) مُعَلِّم هَستَم",
   "lesson": 7
  },
  {
   "id": "w130",
   "phonetic": "shāgerd",
   "english": "student",
   "script": "شاگِرد",
   "lesson": 7
  },
  {
   "id": "w131",
   "phonetic": "mohandes",
   "english": "engineer",
   "script": "مُهَندِس",
   "lesson": 7
  },
  {
   "id": "w132",
   "phonetic": "vakeel",
   "english": "lawyer",
   "script": "وَکیل",
   "lesson": 7
  },
  {
   "id": "w133",
   "phonetic": "neveesandé",
   "english": "writer",
   "script": "نِویسَندِه",
   "lesson": 7
  },
  {
   "id": "w134",
   "phonetic": "me’mār",
   "english": "architect",
   "script": "مِعمار",
   "lesson": 7
  },
  {
   "id": "w135",
   "phonetic": "(man) vakeel hastam",
   "english": "I am a lawyer",
   "script": "(مَن) وََکیل هَستَم",
   "lesson": 7
  },
  {
   "id": "w136",
   "phonetic": "(man) shāgerd hastam",
   "english": "I am a student",
   "script": "(مَن) شاگِرد هَستَم",
   "lesson": 7
  },
  {
   "id": "w137",
   "phonetic": "(shomā) mo’alem hasteen?",
   "english": "are you a teacher? (formal)",
   "script": "(شُما) مُعَلِّم هَستین؟",
   "lesson": 7
  },
  {
   "id": "w138",
   "phonetic": "(shomā) mo’alem hasteen",
   "english": "you are a teacher (formal)",
   "script": "(شُما) مُعَلِّم هستین",
   "lesson": 7
  },
  {
   "id": "w139",
   "phonetic": "(tō) mo’alem hastee",
   "english": "you are a teacher (informal)",
   "script": "(تُو) مُعَلِّم هَستی",
   "lesson": 7
  },
  {
   "id": "w140",
   "phonetic": "(tō) ché kāré hastee?",
   "english": "what do you do? (informal)",
   "script": "(تُو) چِه کارِه هَستی؟",
   "lesson": 7
  },
  {
   "id": "w141",
   "phonetic": "(shomā) ché kāré hasteen?",
   "english": "what do you do? (formal)",
   "script": "(شُما) چِه کارِه هَستین؟",
   "lesson": 7
  },
  {
   "id": "w142",
   "phonetic": "tō chetor?",
   "english": "what about you? (informal)",
   "script": "تُو چِطُور؟",
   "lesson": 7
  },
  {
   "id": "w143",
   "phonetic": "(man) dar edāré kār meekonam",
   "english": "I work in an office",
   "script": "(مَن) دَر اِدارِه کار می‌کُنَم.",
   "lesson": 7
  },
  {
   "id": "w144",
   "phonetic": "restoorān",
   "english": "restaurant",
   "script": "رِستوران",
   "lesson": 7
  },
  {
   "id": "w145",
   "phonetic": "beemārestān",
   "english": "hospital",
   "script": "بیمارِستان",
   "lesson": 7
  },
  {
   "id": "w146",
   "phonetic": "kārkhooné",
   "english": "factory",
   "script": "کارخونِه",
   "lesson": 7
  },
  {
   "id": "w147",
   "phonetic": "(tō) kāret-ō doost dāree?",
   "english": "do you like your job? (informal)",
   "script": "(تُو) کارِتُو دوست داری؟",
   "lesson": 7
  },
  {
   "id": "w148",
   "phonetic": "(shomā) kāretoon-ō doost dāreen?",
   "english": "do you like your job? (formal)",
   "script": "(شُما) کارِتونُو دوست دارین؟",
   "lesson": 7
  },
  {
   "id": "w149",
   "phonetic": "balé, (man) kāram-ō doost dāram",
   "english": "yes, I like my job",
   "script": "بَلِه، (مَن) کارَمُو دوست دارَم",
   "lesson": 7
  },
  {
   "id": "w150",
   "phonetic": "na, (man) kāram-ō doost nadāram",
   "english": "no, I don’t like my job",
   "script": "نَه، (مَن) کارَمُو دوست نَدارَم",
   "lesson": 7
  },
  {
   "id": "w151",
   "phonetic": "(man) kār meekonam",
   "english": "I work",
   "script": "(مَن) کار می‌کُنَم",
   "lesson": 7
  },
  {
   "id": "w152",
   "phonetic": "(man) kār nemeekonam",
   "english": "I don’t work",
   "script": "(مَن) کار نِمی‌کُنَم",
   "lesson": 7
  },
  {
   "id": "w153",
   "phonetic": "(man) beekār-am",
   "english": "I am jobless",
   "script": "(مَن) بیکارَم",
   "lesson": 7
  },
  {
   "id": "w154",
   "phonetic": "(man) bāzneshasté hastam",
   "english": "I am retired",
   "script": "(مَن) بازنِشَستِه هَستَم",
   "lesson": 7
  },
  {
   "id": "w155",
   "phonetic": "hesābdār",
   "english": "accountant",
   "script": "حِسابدار",
   "lesson": 7
  },
  {
   "id": "w156",
   "phonetic": "āshpaz",
   "english": "cook",
   "script": "آشپَز",
   "lesson": 7
  },
  {
   "id": "w157",
   "phonetic": "gārson",
   "english": "waiter",
   "script": "گارسُن",
   "lesson": 7
  },
  {
   "id": "w158",
   "phonetic": "dandoon pezeshk",
   "english": "dentist",
   "script": "دَندونپِزِشک",
   "lesson": 7
  },
  {
   "id": "w159",
   "phonetic": "khalabān",
   "english": "pilot",
   "script": "خَلَبان",
   "lesson": 7
  },
  {
   "id": "w160",
   "phonetic": "honarmand",
   "english": "artist",
   "script": "هُنَرمَند",
   "lesson": 7
  },
  {
   "id": "w161",
   "phonetic": "(shomā) kāretoon-ō doost dareen?",
   "english": "do you like your job? (formal)",
   "script": "(شُما) کارِتونُو دوست دارین؟",
   "lesson": 8
  },
  {
   "id": "w162",
   "phonetic": "doost dāram",
   "english": "I like",
   "script": "دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w163",
   "phonetic": "(man) shokolāt doost dāram",
   "english": "I like chocolate",
   "script": "(مَن) شُکُلات دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w164",
   "phonetic": "(man) tabee’at doost dāram",
   "english": "I like nature",
   "script": "(مَن) طَبیعَت دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w165",
   "phonetic": "(man) varzesh doost dāram",
   "english": "I like sports",
   "script": "(مَن) وَرزِش دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w166",
   "phonetic": "(man) mooseeghee doost dāram",
   "english": "I like music",
   "script": "(مَن) موسیقی دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w167",
   "phonetic": "(man) chārlee chāpleen-rā doost dāram",
   "english": "I like Charlie Chaplin",
   "script": "(مَن) چارلی چاپلین را دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w168",
   "phonetic": "(man) chārlee chāpleen-ō doost dāram",
   "english": "I like Charlie Chaplin",
   "script": "(مَن) چارلی چاپلینُو دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w169",
   "phonetic": "(man) doost dāram feelm bebeenam",
   "english": "I like to watch movies",
   "script": "(مَن) دوست دارَم فیلم بِبینَم.",
   "lesson": 8
  },
  {
   "id": "w170",
   "phonetic": "(man) doost dāram ketāb bekhoonam",
   "english": "I like to read books",
   "script": "(مَن) دوست دارَم کِتاب بِخونَم",
   "lesson": 8
  },
  {
   "id": "w171",
   "phonetic": "(man) doost dāram varzesh bokonam",
   "english": "I like to exercise",
   "script": "(مَن) دوست دارَم وَرزِش بُکُنَم",
   "lesson": 8
  },
  {
   "id": "w172",
   "phonetic": "(man) doost dāram shokolāt bokhoram",
   "english": "I like to eat chocolate",
   "script": "(مَن) دوست دارَم شُکُلات بُخورَم",
   "lesson": 8
  },
  {
   "id": "w173",
   "phonetic": "(man) doost dāram fārsi yād begeeram",
   "english": "I like to learn Persian",
   "script": "(مَن) دوست دارَم فارسی یاد بِگیرَم",
   "lesson": 8
  },
  {
   "id": "w174",
   "phonetic": "(man) shokolāt khaylee doost dāram",
   "english": "I really like chocolate",
   "script": "(مَن) شُکُلات خِیلی دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w175",
   "phonetic": "(man) chārlee chāpleen-ō khaylee doost dāram",
   "english": "I really like Charlie Chaplin",
   "script": "(مَن) چارلی چاپلینُو خِیلی دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w176",
   "phonetic": "(man) khaylee doost dāram feelm bebeenam",
   "english": "I really like to watch movies",
   "script": "(مَن) خِیلی دوست دارَم فیلم بِبینَم",
   "lesson": 8
  },
  {
   "id": "w177",
   "phonetic": "(man) khaylee doost dāram shokolāt bokhoram",
   "english": "I really like to eat chocolate",
   "script": "(مَن) خِیلی دوست دارَم شُکُلات بُخورَم",
   "lesson": 8
  },
  {
   "id": "w178",
   "phonetic": "(man) kāram-ō doost nadāram",
   "english": "I do not like my job",
   "script": "(مَن) کارَمُو دوست نَدارَم",
   "lesson": 8
  },
  {
   "id": "w179",
   "phonetic": "(man) shokolāt doost nadāram",
   "english": "I do not like chocolate",
   "script": "(مَن) شُکُلات دوست نَدارَم",
   "lesson": 8
  },
  {
   "id": "w180",
   "phonetic": "(man) tabee’at doost nadāram",
   "english": "I do not like nature",
   "script": "(مَن) طَبیعَت دوست نَدارَم",
   "lesson": 8
  },
  {
   "id": "w181",
   "phonetic": "(man) doost nadāram ketāb bekhoonam",
   "english": "I do not like to read books",
   "script": "(مَن) دوست نَدارَم کِتاب بِخونَم",
   "lesson": 8
  },
  {
   "id": "w182",
   "phonetic": "(man) doost nadāram varzesh bokonam",
   "english": "I do not like to exercise",
   "script": "(مَن) دوست نَدارَم وَرزِش بُکُنَم",
   "lesson": 8
  },
  {
   "id": "w183",
   "phonetic": "ché kārhāyee doost dāree bokonee?",
   "english": "what do you like to do? (informal)",
   "script": "چِه كارهايي دوست دارى بُکُنى؟",
   "lesson": 8
  },
  {
   "id": "w184",
   "phonetic": "ché kārhāyee doost dāreen bokoneen?",
   "english": "what do you like to do? (formal)",
   "script": "چِه کارهایی دوست دارین بُکُنین؟",
   "lesson": 8
  },
  {
   "id": "w185",
   "phonetic": "āshpazee doost dāram",
   "english": "I like cooking",
   "script": "آشپَزی دوست دارَم",
   "lesson": 8
  },
  {
   "id": "w186",
   "phonetic": "doost dāram piāno bezanam",
   "english": "I like to play piano",
   "script": "دوست دارَم پیانُو بِزَنَم",
   "lesson": 8
  },
  {
   "id": "w187",
   "phonetic": "doost dāram geetār bezanam",
   "english": "I like to play guitar",
   "script": "دوست دارَم گیتار بِزَنَم",
   "lesson": 8
  },
  {
   "id": "w188",
   "phonetic": "doost dāram footbāl bāzee bokonam",
   "english": "I like to play football",
   "script": "دوست دارَم فوتبال بازی بُکُنَم",
   "lesson": 8
  },
  {
   "id": "w189",
   "phonetic": "(shomā) chetor-een?",
   "english": "how are you? (formal)",
   "script": "(شُما) چِطُورین؟",
   "lesson": 9
  },
  {
   "id": "w190",
   "phonetic": "esmam matt-é",
   "english": "my name is Matt (name ending with consonant)",
   "script": "اِسمَم مَتِّه",
   "lesson": 9
  },
  {
   "id": "w191",
   "phonetic": "esmam leylā-st",
   "english": "my name is Leyla (name ending with vowel)",
   "script": "اِسمَم لِیلاست",
   "lesson": 9
  },
  {
   "id": "w192",
   "phonetic": "khānevādé",
   "english": "family",
   "script": "خانِوادِه",
   "lesson": 9
  },
  {
   "id": "w193",
   "phonetic": "khālé",
   "english": "aunt (maternal)",
   "script": "خالِه",
   "lesson": 9
  },
  {
   "id": "w194",
   "phonetic": "dokhtar khālé",
   "english": "girl cousin (from maternal aunt)",
   "script": "دُختَرخالِه",
   "lesson": 9
  },
  {
   "id": "w195",
   "phonetic": "pesar khālé",
   "english": "boy cousin (from maternal aunt)",
   "script": "پِسَرخالِه",
   "lesson": 9
  },
  {
   "id": "w196",
   "phonetic": "dokhtar amé",
   "english": "girl cousin (from paternal aunt)",
   "script": "دُختَرعَمِّه",
   "lesson": 9
  },
  {
   "id": "w197",
   "phonetic": "pesar amé",
   "english": "boy cousin (from paternal aunt)",
   "script": "پِسَرعَمِّه",
   "lesson": 9
  },
  {
   "id": "w198",
   "phonetic": "dokhtar dāyee",
   "english": "girl cousin (from maternal uncle)",
   "script": "دُختَر‌دایی",
   "lesson": 9
  },
  {
   "id": "w199",
   "phonetic": "pesar dāyee",
   "english": "boy cousin (from maternal uncle)",
   "script": "پِسَردایی",
   "lesson": 9
  },
  {
   "id": "w200",
   "phonetic": "dokhtar amoo",
   "english": "girl cousin (from paternal uncle)",
   "script": "دُختَرعَمو",
   "lesson": 9
  },
  {
   "id": "w201",
   "phonetic": "pesar amoo",
   "english": "boy cousin (from paternal uncle)",
   "script": "پِسَرعَمو",
   "lesson": 9
  },
  {
   "id": "w202",
   "phonetic": "kay",
   "english": "when",
   "script": "کِی",
   "lesson": 9
  },
  {
   "id": "w203",
   "phonetic": "kojā",
   "english": "where",
   "script": "کُجا",
   "lesson": 9
  },
  {
   "id": "w204",
   "phonetic": "chee",
   "english": "what",
   "script": "چي",
   "lesson": 9
  },
  {
   "id": "w205",
   "phonetic": "chetor",
   "english": "how",
   "script": "چِطُور",
   "lesson": 9
  },
  {
   "id": "w206",
   "phonetic": "kodoom",
   "english": "which",
   "script": "کُدوم",
   "lesson": 9
  },
  {
   "id": "w207",
   "phonetic": "kojā-yee?",
   "english": "where are you? (informal)",
   "script": "کُجایی؟",
   "lesson": 9
  },
  {
   "id": "w208",
   "phonetic": "kojā-yeen?",
   "english": "where are you? (formal)",
   "script": "کُجایین؟",
   "lesson": 9
  },
  {
   "id": "w209",
   "phonetic": "chee doost dāree?",
   "english": "what do (would) you like?",
   "script": "چی دوست داری؟",
   "lesson": 9
  },
  {
   "id": "w210",
   "phonetic": "een kee-yé?",
   "english": "who is this?",
   "script": "این کیِه؟",
   "lesson": 9
  },
  {
   "id": "w211",
   "phonetic": "cherā na?",
   "english": "why not?",
   "script": "چِرا نَه؟",
   "lesson": 9
  },
  {
   "id": "w212",
   "phonetic": "chand",
   "english": "how many",
   "script": "چَند؟",
   "lesson": 9
  },
  {
   "id": "w213",
   "phonetic": "chand tā",
   "english": "how many (colloquial)",
   "script": "چَند تا",
   "lesson": 9
  },
  {
   "id": "w214",
   "phonetic": "chegooné",
   "english": "how (more literary)",
   "script": "چِگونِه",
   "lesson": 9
  },
  {
   "id": "w215",
   "phonetic": "koo?",
   "english": "where is it? (colloquial)",
   "script": "کو؟",
   "lesson": 9
  },
  {
   "id": "w216",
   "phonetic": "chee-yé?",
   "english": "what is it?",
   "script": "چیِه؟",
   "lesson": 9
  },
  {
   "id": "w217",
   "phonetic": "chetor-é?",
   "english": "how is he/she?",
   "script": "چِطُورِه؟",
   "lesson": 9
  },
  {
   "id": "w218",
   "phonetic": "cheghadr",
   "english": "how much",
   "script": "چِِقَدر؟",
   "lesson": 9
  },
  {
   "id": "w219",
   "phonetic": "az ___ hasteem",
   "english": "we are from ___",
   "script": "اَز___ هَستیم",
   "lesson": 10
  },
  {
   "id": "w220",
   "phonetic": "dar ___ zendegee meekoneem",
   "english": "we live in ____",
   "script": "دَر___ زِندِگی می‌کُنیم",
   "lesson": 10
  },
  {
   "id": "w221",
   "phonetic": "bé hamcheneen",
   "english": "likewise",
   "script": "بِه‌ هَمچِنین",
   "lesson": 10
  }
 ],
 "dialogues": [
  {
   "lesson": 1,
   "name": "Conversation 1",
   "lines": [
    {
     "speaker": "Leyla",
     "phonetic": "salām matt, chetor-ee?",
     "script": "سَلام مَت، چِطوری؟"
    },
    {
     "speaker": "Matt",
     "phonetic": "khoob-am, merci, chetor-ee?",
     "script": "خوبَم، مِرسی، چِطوری؟"
    },
    {
     "speaker": "Leyla",
     "phonetic": "khoob-am, merci.",
     "script": "خوبَم، مِرسی"
    }
   ]
  },
  {
   "lesson": 1,
   "name": "Conversation 2",
   "lines": [
    {
     "speaker": "Leyla",
     "phonetic": "salām matt, chetor-ee?",
     "script": "سَلام مَت، چِطوری؟"
    },
    {
     "speaker": "Matt",
     "phonetic": "khoob-am, merci, chetor-ee?",
     "script": "خوبَم، مِرسی، چِطوری؟"
    },
    {
     "speaker": "Leyla",
     "phonetic": "man khoob neestam.",
     "script": "مَن خوب نیستَم"
    }
   ]
  },
  {
   "lesson": 2,
   "name": "Conversation",
   "lines": [
    {
     "speaker": "leylā",
     "phonetic": "salām, sobh bekhayr.",
     "script": "سَلام، صُبح بِخِیر",
     "english": "Hello, good morning."
    },
    {
     "speaker": "matt",
     "phonetic": "salām, sobh bekhayr.",
     "script": "سَلام، صُبح بِخِیر",
     "english": "Hello, good morning."
    },
    {
     "speaker": "leylā",
     "phonetic": "chetor-ee?",
     "script": "چِطوری؟",
     "english": "How are you?"
    },
    {
     "speaker": "matt",
     "phonetic": "khoob-am, merci. chetor-ee?",
     "script": "خوبَم مِرسی، چِطوری؟",
     "english": "I am well, thanks. How are you?"
    },
    {
     "speaker": "leylā",
     "phonetic": "khoob-am, merci. esmé man leylā hast.",
     "script": "خوبَم مِرسی. اِسمِ مَن لِیلا هَست",
     "english": "I am well, thanks. My name is Leyla."
    },
    {
     "speaker": "matt",
     "phonetic": "esmé man matt hast.",
     "script": "اِسمِ مَن مَت هَست",
     "english": "My name is Matt."
    },
    {
     "speaker": "leylā",
     "phonetic": "khoshvaghtam!",
     "script": "خوشوَقتَم",
     "english": "I’m pleased (to meet you)."
    },
    {
     "speaker": "matt",
     "phonetic": "khoshvaghtam.",
     "script": "خوشوَقتَم",
     "english": "I’m pleased (to meet you)."
    }
   ],
   "questions": [
    {
     "q": "What are Leyla and Matt doing?",
     "a": "Greeting and introducing themselves",
     "d": [
      "Saying goodbye",
      "Talking about their jobs",
      "Introducing their families"
     ],
     "lines": [
      3,
      4,
      5
     ]
    },
    {
     "q": "How is Matt feeling?",
     "a": "Well",
     "d": [
      "Not well",
      "Tired",
      "Angry"
     ],
     "lines": [
      2,
      3
     ]
    }
   ]
  },
  {
   "lesson": 3,
   "name": "Conversation 1",
   "lines": [
    {
     "speaker": "Leyla",
     "phonetic": "salām, sobh bekhayr.",
     "script": "سَلام، صُبح بِخِیر"
    },
    {
     "speaker": "Matt",
     "phonetic": "salām, esmé man matt hast. esmé tō chee-yé?",
     "script": "سَلام، اِسمِ مَن مَت هَست. اِسمِ تُو چیِه؟"
    },
    {
     "speaker": "Leyla",
     "phonetic": "esmé man leyla hast.",
     "script": "اِسمِ مَن لِیلا هَست"
    },
    {
     "speaker": "Matt",
     "phonetic": "khoshvaghtam.",
     "script": "خوشوَقتَم"
    }
   ]
  },
  {
   "lesson": 3,
   "name": "Conversation 2",
   "lines": [
    {
     "speaker": "Leyla",
     "phonetic": "salām, rooz bekhayr.",
     "script": "سَلام، روز بِخِیر"
    },
    {
     "speaker": "Matt",
     "phonetic": "rooz bekhayr. esmé shomā chee-yé?",
     "script": "روز بِخِیر. اِسمِ شُما چیِه؟"
    },
    {
     "speaker": "Leyla",
     "phonetic": "esmé man leyla hast.",
     "script": "اِسمِ مَن لِیلا هَست"
    },
    {
     "speaker": "Matt",
     "phonetic": "esmé man matt hast.",
     "script": "اِسمِ مَن مَت هَست"
    },
    {
     "speaker": "Leyla",
     "phonetic": "khoshvaghtam.",
     "script": "خوشوَقتَم"
    },
    {
     "speaker": "Matt",
     "phonetic": "khoshvaghtam.",
     "script": "خوشوَقتَم"
    }
   ]
  },
  {
   "lesson": 3,
   "name": "Conversation 3",
   "lines": [
    {
     "speaker": "leylā",
     "phonetic": "salām, chetor-ee?",
     "script": "سَلام، چِطوری؟",
     "english": "Hello, how are you?"
    },
    {
     "speaker": "matt",
     "phonetic": "khoob-am, merci. tō chetor-ee?",
     "script": "خوبَم مِرسی، تو چِطوری؟",
     "english": "I’m good, thanks. How are you?"
    },
    {
     "speaker": "leylā",
     "phonetic": "bad neestam. esmé tō chee-yé?",
     "script": "بَد نیستَم. اِسمِ تو چیِه؟",
     "english": "Not bad. What’s your name?"
    },
    {
     "speaker": "matt",
     "phonetic": "esmé man matt hast.",
     "script": "اِسمِ مَن مَت هَست",
     "english": "My name is Matt."
    },
    {
     "speaker": "leylā",
     "phonetic": "tō ahlé kojā hastee, matt?",
     "script": "تو اَهلِ کُجا هَستی، مَت؟",
     "english": "Where are you from, Matt?"
    },
    {
     "speaker": "matt",
     "phonetic": "man ahlé āmreekā hastam. tō ahlé kojā hastee?",
     "script": "مَن اَهلِ آمریکا هَستَم. تو اَهلِ کُجا هَستی؟",
     "english": "I am from the United States. Where are you from?"
    },
    {
     "speaker": "leylā",
     "phonetic": "man ham ahlé āmreekā hastam!",
     "script": "مَن هَم اَهلِ آمریکا هَستَم",
     "english": "I am also from the United States!"
    }
   ],
   "questions": [
    {
     "q": "Where is Matt from?",
     "a": "The United States",
     "d": [
      "Iran",
      "Mexico",
      "Esfahan"
     ],
     "lines": [
      4,
      5
     ]
    },
    {
     "q": "Where is Leyla from?",
     "a": "The United States",
     "d": [
      "Iran",
      "France",
      "Paris"
     ],
     "lines": [
      5,
      6
     ]
    },
    {
     "q": "How does Leyla say she's feeling?",
     "a": "Not bad",
     "d": [
      "Wonderful",
      "Terrible",
      "Sleepy"
     ],
     "lines": [
      1,
      2
     ]
    }
   ]
  },
  {
   "lesson": 4,
   "name": "Conversation 1",
   "lines": [
    {
     "speaker": "Leyla",
     "phonetic": "salām!",
     "script": "سَلام"
    },
    {
     "speaker": "Matt",
     "phonetic": "salām, esmé shomā chee-yé?",
     "script": "سَلام، اِسمِ شُما چیِه؟"
    },
    {
     "speaker": "Leyla",
     "phonetic": "esmé man leylā hast. va shomā?",
     "script": "اِسمِ مَن لِیلا هَست. وَ شُما؟"
    },
    {
     "speaker": "Matt",
     "phonetic": "esmé man matt hast. shomā az āmreekā hasteen?",
     "script": "اِسمِ مَن مَت هَست. شُما اَز آمریکا هَستین؟"
    },
    {
     "speaker": "Leyla",
     "phonetic": "balé, man az āmreekā hastam.",
     "script": ".بَلِه، اَز آمریکا هَستَم"
    }
   ]
  },
  {
   "lesson": 4,
   "name": "Conversation 2",
   "lines": [
    {
     "speaker": "Matt",
     "phonetic": "salām, sobh bekhayr.",
     "script": "سَلام، صُبح بِخِیر"
    },
    {
     "speaker": "Leyla",
     "phonetic": "salām, esmé tō chee-yé?",
     "script": "سَلام، اِسمِ تُو چیِه؟"
    },
    {
     "speaker": "Matt",
     "phonetic": "man matt hastam.",
     "script": "مَن مَت هَستَم"
    },
    {
     "speaker": "Leyla",
     "phonetic": "tō az āmreekā hastee?",
     "script": "تُو اَز آمریکا هَستی؟"
    },
    {
     "speaker": "Matt",
     "phonetic": "na, man az āmreekā neestam. man az eerān hastam.",
     "script": "نَه، مَن اَز آمریکا نیستَم. مَن اَز ایران هَستَم"
    }
   ]
  },
  {
   "lesson": 4,
   "name": "Conversation 4",
   "lines": [
    {
     "speaker": "leylā",
     "phonetic": "salām.",
     "script": "سَلام",
     "english": "Hello."
    },
    {
     "speaker": "matt",
     "phonetic": "asr bekhayr. chetor-ee?",
     "script": "عَصر بِخِیر. چِطوری؟",
     "english": "Good afternoon. How are you?"
    },
    {
     "speaker": "leylā",
     "phonetic": "khoob-am, merci.",
     "script": "خوبَم، مِرسی",
     "english": "I’m good, thanks."
    },
    {
     "speaker": "matt",
     "phonetic": "esmé tō chee-yé?",
     "script": "اِسمِ تُو چیِه؟",
     "english": "What is your name?"
    },
    {
     "speaker": "leylā",
     "phonetic": "esmé man leylā hast. esmé tō chee-yé?",
     "script": "اِسمِ مَن لِیلا هَست. اِسمِ تُو چیِه؟",
     "english": "My name is Leyla. What is your name?"
    },
    {
     "speaker": "matt",
     "phonetic": "esmé man matt hast.",
     "script": "اِسمِ مَن مَت هَست",
     "english": "My name is Matt."
    },
    {
     "speaker": "leylā",
     "phonetic": "az eerān hastee?",
     "script": "اَز ایران هَستی؟",
     "english": "Are you from Iran?"
    },
    {
     "speaker": "matt",
     "phonetic": "na, man az eerān neestam. man az āmreekā hastam. tō ham az āmreekā hastee?",
     "script": "نَه، مَن اَز ایران نیستَم. مَن اَز آمریکا هَستَم. تُو هَم اَز آمریکا هَستی؟",
     "english": "No, I am not from Iran. I am from the United States. Are you also from the United States?"
    },
    {
     "speaker": "leylā",
     "phonetic": "man az eerān hastam, valee hālā dar āmreekā zendegee meekonam.",
     "script": "مَن اَز ایران هَستَم، ولی حالا دَر آمریکا زِندِگی می‌کُنَم",
     "english": "I am from Iran, but now I live in the United States."
    }
   ],
   "questions": [
    {
     "q": "Where is Leyla from?",
     "a": "Iran",
     "d": [
      "The United States",
      "France",
      "Mexico"
     ],
     "lines": [
      8
     ]
    },
    {
     "q": "Where does Leyla live now?",
     "a": "The United States",
     "d": [
      "Iran",
      "Paris",
      "Shiraz"
     ],
     "lines": [
      8
     ]
    },
    {
     "q": "Where is Matt from?",
     "a": "The United States",
     "d": [
      "Iran",
      "Turkey",
      "Esfahan"
     ],
     "lines": [
      6,
      7
     ]
    }
   ]
  },
  {
   "lesson": 5,
   "name": "Conversation 1",
   "lines": [
    {
     "speaker": "Sam",
     "phonetic": "salām, sobh bekhayr.",
     "script": "سَلام، صُبح بِخِیر"
    },
    {
     "speaker": "Maryam",
     "phonetic": "salām. man maryam hastam. esmé tō chee-yé?",
     "script": "سَلام. مَن مَریَم هَستَم. اِسمِ تُو چیِه؟"
    },
    {
     "speaker": "Sam",
     "phonetic": "esmé man sām hast. een zané man-é va een pesaré man-é.",
     "script": "اِسمِ مَن سام هَست. این زَنِ مَنِه وَ این پِسَرِ مَنِه"
    },
    {
     "speaker": "Maryam",
     "phonetic": "khoshvaghtam. een shoharé man-é va een dokhtaré man-é.",
     "script": "خوشوَقتَم. این شوهَرِ مَنِه وَ این دُختَرِ مَنِه"
    }
   ]
  },
  {
   "lesson": 5,
   "name": "Conversation 2",
   "lines": [
    {
     "speaker": "Sam",
     "phonetic": "salām, sobh bekhayr.",
     "script": "سَلام، صُبح بِخِیر"
    },
    {
     "speaker": "Maryam",
     "phonetic": "salām. man maryam hastam va eeshoon mādaré man-and.",
     "script": "سَلام. مَن مَریَم هَستَم وَ ایشون مادَرِ مَن‌اَند"
    },
    {
     "speaker": "Sam",
     "phonetic": "khoshvaghtam. esmé man sām hast va een barādaré man-é.",
     "script": "خوشوَقتَم. اِسمِ مَن سام هَست وَ این بَرادَرِ مَنِه"
    },
    {
     "speaker": "Maryam",
     "phonetic": "khoshvaghtam.",
     "script": "خوشوَقتَم"
    }
   ]
  },
  {
   "lesson": 5,
   "name": "Conversation 3",
   "lines": [
    {
     "speaker": "shirin",
     "phonetic": "salām, sobh bekhayr.",
     "script": "سَلام، صُبح بِخِیر",
     "english": "Hello, good morning."
    },
    {
     "speaker": "pedrām",
     "phonetic": "salām. chetor-ee?",
     "script": "سَلام، چِطُوری؟",
     "english": "Hello. How are you?"
    },
    {
     "speaker": "shirin",
     "phonetic": "khoob-am, merci. tō chetor-ee?",
     "script": "خوبَم، مِرسی. تُو چِطُوری؟",
     "english": "I’m well, thank you. How are you?"
    },
    {
     "speaker": "pedrām",
     "phonetic": "khoob-am. esmé tō chee-yé?",
     "script": "خوبَم. اِسمِ تُو چیِه؟",
     "english": "I’m well. What’s your name?"
    },
    {
     "speaker": "shirin",
     "phonetic": "esmé man shirin hast. esmé tō chee-yé?",
     "script": "اِسمِ مَن شیرین هَست. اِسمِ تُو چیِه؟",
     "english": "My name is Shirin. What’s your name?"
    },
    {
     "speaker": "pedrām",
     "phonetic": "esmé man pedrām hast.",
     "script": "اِسمِ مَن پِدرام هَست",
     "english": "My name is Pedrām."
    },
    {
     "speaker": "shirin",
     "phonetic": "ahlé kojā hastee pedrām?",
     "script": "اَهلِ کُجا هَستی پِدرام؟",
     "english": "Where are you from, Pedrām?"
    },
    {
     "speaker": "pedrām",
     "phonetic": "man ahlé esfahān hastam.",
     "script": "مَن اَهلِ اِصفَهان هَستَم",
     "english": "I am from Esfāhān."
    },
    {
     "speaker": "shirin",
     "phonetic": "man ham ahlé esfahān hastam, valee hālā dar pāris zendegee meekonam.",
     "script": "مَن هَم اَهلِ اِصفَهان هَستَم، وَلی حالا دَر پاریس زِندِگی می‌کُنَم",
     "english": "I am also from Esfāhān, but now I live in Paris."
    },
    {
     "speaker": "pedrām",
     "phonetic": "een zané man-é. esmesh marjān-é.",
     "script": "این زَنِ مَنِه. اِسمِش مَرجانِه",
     "english": "This is my wife. Her name is Marjān."
    },
    {
     "speaker": "shirin",
     "phonetic": "salām marjān. va een shoharé man-é. esmesh madani-yé.",
     "script": "سَلام مَرجان. وَ این شُوهَرِ مَنِه. اِسمِش مَدَنیِه",
     "english": "Hello Marjān. And this is my husband. His name is Madani."
    },
    {
     "speaker": "pedrām",
     "phonetic": "va een ham pesaré man-é. esmesh bābak-é.",
     "script": "وَ این هَم پِسَرِ مَنِه. اِسمِش بابَکِه",
     "english": "And this is my son. His name is Bābak."
    }
   ],
   "questions": [
    {
     "q": "Where is Pedram from?",
     "a": "Esfahan",
     "d": [
      "Paris",
      "Tehran",
      "Shiraz"
     ],
     "lines": [
      6,
      7
     ]
    },
    {
     "q": "Where does Shirin live now?",
     "a": "Paris",
     "d": [
      "Esfahan",
      "Iran",
      "The United States"
     ],
     "lines": [
      8
     ]
    },
    {
     "q": "What is the name of Pedram's wife?",
     "a": "Marjan",
     "d": [
      "Shirin",
      "Donna",
      "Seema"
     ],
     "lines": [
      9
     ]
    },
    {
     "q": "Who is Babak?",
     "a": "Pedram's son",
     "d": [
      "Pedram's brother",
      "Shirin's husband",
      "Pedram's father"
     ],
     "lines": [
      11
     ]
    }
   ]
  },
  {
   "lesson": 6,
   "name": "Conversation 1",
   "lines": [
    {
     "speaker": "farzāné",
     "phonetic": "alō?",
     "script": "اَلُو؟",
     "english": "Hello?"
    },
    {
     "speaker": "leylā",
     "phonetic": "salām!",
     "script": "سَلام",
     "english": "Hello!"
    },
    {
     "speaker": "farzāné",
     "phonetic": "salām!",
     "script": "سَلام",
     "english": "Hello!"
    },
    {
     "speaker": "leylā",
     "phonetic": "esmé shomā chee-yé?",
     "script": "اِسمِ شُما چیِه؟",
     "english": "What is your name?"
    },
    {
     "speaker": "farzāné",
     "phonetic": "man farzāné hastam.",
     "script": "مَن فرزانِه هَستَم",
     "english": "I am Farzaneh."
    },
    {
     "speaker": "leylā",
     "phonetic": "shomā kee hasteen?",
     "script": "شُما کی هَستین؟",
     "english": "Who are you?"
    },
    {
     "speaker": "farzāné",
     "phonetic": "man mādaré tō hastam.",
     "script": "مَن مادَرِ تُو هَستَم",
     "english": "I am your mother."
    },
    {
     "speaker": "leylā",
     "phonetic": "salām māmān! balé, shomā mādaré man hasteen, va man dokhtaré shomā hastam.",
     "script": "سَلام مامان! بَلِه، شُما مادَرِ مَن هَستین وَ مَن دُختَرِ شُما هَستَم",
     "english": "Hello mother! Yes, you are my mother, and I am your daughter."
    }
   ],
   "questions": [
    {
     "q": "Who is Farzaneh?",
     "a": "Leyla's mother",
     "d": [
      "Leyla's sister",
      "Leyla's friend",
      "Leyla's teacher"
     ],
     "lines": [
      5,
      6
     ]
    },
    {
     "q": "What is the relationship between the two speakers?",
     "a": "Mother and daughter",
     "d": [
      "Sisters",
      "Teacher and student",
      "Neighbours"
     ],
     "lines": [
      6,
      7
     ]
    }
   ]
  },
  {
   "lesson": 7,
   "name": "Conversation 1",
   "lines": [
    {
     "speaker": "leylā",
     "phonetic": "salām, man mo’alem hastam.",
     "script": "سَلام، مَن مُعَلِّم هَستَم",
     "english": "Hello, I am a teacher."
    },
    {
     "speaker": "matt",
     "phonetic": "salām!",
     "script": "سَلام",
     "english": "Hello!"
    },
    {
     "speaker": "leylā",
     "phonetic": "tō chetor? tō ham mo’alem hastee?",
     "script": "تُو چِطُور؟ تُو هَم مُعَلِّم هَستی؟",
     "english": "What about you? Are you also a teacher?"
    },
    {
     "speaker": "matt",
     "phonetic": "na, man mo’alem neestam.",
     "script": "نَه، مَن مُعَلِّم نیستَم",
     "english": "No, I'm not a teacher."
    },
    {
     "speaker": "leylā",
     "phonetic": "ché kāré hastee?",
     "script": "چِه کارِه هَستی؟",
     "english": "What do you do?"
    },
    {
     "speaker": "matt",
     "phonetic": "man vakeel hastam.",
     "script": "مَن وَکیل هَستَم",
     "english": "I am a lawyer."
    }
   ],
   "questions": [
    {
     "q": "What is Leyla's job?",
     "a": "Teacher",
     "d": [
      "Lawyer",
      "Doctor",
      "Student"
     ],
     "lines": [
      0
     ]
    },
    {
     "q": "What is Matt's job?",
     "a": "Lawyer",
     "d": [
      "Teacher",
      "Doctor",
      "Architect"
     ],
     "lines": [
      4,
      5
     ]
    }
   ]
  },
  {
   "lesson": 7,
   "name": "Conversation 2",
   "lines": [
    {
     "speaker": "sārā",
     "phonetic": "salām! esmé man sārā hast.",
     "script": "سَلام! اِسمِ مَن سارا هَست",
     "english": "Hello! My name is Sara."
    },
    {
     "speaker": "dāneeyel",
     "phonetic": "salām! man dāneeyel hastam.",
     "script": "سلام! مَن دانییِل هَستَم",
     "english": "Hello! I am Daniel."
    },
    {
     "speaker": "sārā",
     "phonetic": "dāneeyel, ché kāré hastee?",
     "script": "دانییِل، چِه کارِه هَستی؟",
     "english": "Daniel, what do you do?"
    },
    {
     "speaker": "dāneeyel",
     "phonetic": "man doktor hastam.",
     "script": "مَن دُکتُر هَستَم",
     "english": "I am a doctor."
    },
    {
     "speaker": "sārā",
     "phonetic": "kojā kār meekonee?",
     "script": "کُجا کار می‌کُنی؟",
     "english": "Where do you work?"
    },
    {
     "speaker": "dāneeyel",
     "phonetic": "dar beemārestan kār meekonam.",
     "script": "دَر بیمارِستان کار می‌کُنَم",
     "english": "I work in a hospital."
    },
    {
     "speaker": "sārā",
     "phonetic": "kāret-ō doost dāree?",
     "script": "کارِتُو دوست داری؟",
     "english": "Do you like your job?"
    },
    {
     "speaker": "dāneeyel",
     "phonetic": "balé, khaylee kāram-ō doost dāram.",
     "script": "بَلِه، خِیلی کارَمُو دوست دارَم",
     "english": "Yes, I like my job a lot."
    }
   ],
   "questions": [
    {
     "q": "What is Daniel's job?",
     "a": "Doctor",
     "d": [
      "Teacher",
      "Lawyer",
      "Architect"
     ],
     "lines": [
      2,
      3
     ]
    },
    {
     "q": "Where does Daniel work?",
     "a": "In a hospital",
     "d": [
      "In a school",
      "In an office",
      "In a restaurant"
     ],
     "lines": [
      4,
      5
     ]
    },
    {
     "q": "Does Daniel like his job?",
     "a": "Yes, a lot",
     "d": [
      "No",
      "Only a little",
      "He doesn't say"
     ],
     "lines": [
      6,
      7
     ]
    }
   ]
  },
  {
   "lesson": 8,
   "name": "Conversation 1",
   "lines": [
    {
     "speaker": "leylā",
     "phonetic": "salām matt. chetor-ee?",
     "script": "سَلام مَت، چِطُوری؟",
     "english": "Hello Matt. How are you?"
    },
    {
     "speaker": "matt",
     "phonetic": "salām leylā, bad neestam. tō chetor-ee?",
     "script": "سَلام لِیلا، بَد نیستَم. تو چِطُوری؟",
     "english": "Hi Leyla. I’m not bad. How are you?"
    },
    {
     "speaker": "leylā",
     "phonetic": "khoob-am, merci.",
     "script": "خوبَم، مِرسی",
     "english": "I’m good, thanks."
    },
    {
     "speaker": "matt",
     "phonetic": "bebeenam leylā, che kāré hastee?",
     "script": "بِبینَم لِیلا، چِکارِه هَستی؟",
     "english": "Let’s see, Leyla, what do you do?"
    },
    {
     "speaker": "leylā",
     "phonetic": "man me’mār hastam va fārsi ham dars meedam. tō chetor, che kāré hastee?",
     "script": "مَن مِعمار هَستَم وَ فارسی هَم دَرس می‌دَم. تُو چِطُور، چِکارِه هَستی؟",
     "english": "I am an architect, and I also teach Persian. What about you, what do you do?"
    },
    {
     "speaker": "matt",
     "phonetic": "man kār nadāram. shāgerd hastam. fārsi yād meegeeram.",
     "script": "مَن کار نَدارَم. شاگِرد هَستَم. فارسی یاد می‌گیرَم",
     "english": "I don’t have a job. I am a student. I am learning Persian."
    },
    {
     "speaker": "leylā",
     "phonetic": "khaylee khoob-é.",
     "script": "خِیلی خوبِه",
     "english": "That’s great."
    },
    {
     "speaker": "matt",
     "phonetic": "kāret-ō doost dāree?",
     "script": "کارِتُو دوست داری؟",
     "english": "Do you like your job?"
    },
    {
     "speaker": "leylā",
     "phonetic": "khaylee kāram-ō doost dāram. va doost daram ketāb bekhoonam va varzesh bokonam.",
     "script": "خِیلی کارَمُو دوست دارَم. وَ دوست دارَم کِتاب بِخونَم وَ وَرزِش بُکُنَم",
     "english": "I really like my job. And I like to read books, and I like to exercise."
    },
    {
     "speaker": "matt",
     "phonetic": "man ham khaylee doost dāram varzesh bokonam va khaylee doost dāram fārsi yād begeeram.",
     "script": "مَن هَم خِیلی دوست دارَم وَرزِش بُکُنَم وَ خِیلی دوست دارَم فارسی یاد بِگیرَم",
     "english": "I also really like to exercise, and I really like to learn Persian."
    }
   ],
   "questions": [
    {
     "q": "What is Leyla's job?",
     "a": "Architect",
     "d": [
      "Doctor",
      "Teacher",
      "Lawyer"
     ],
     "lines": [
      3,
      4
     ]
    },
    {
     "q": "Does Matt have a job?",
     "a": "No",
     "d": [
      "Yes",
      "He is a teacher"
     ],
     "lines": [
      5
     ]
    },
    {
     "q": "What does Leyla like to do?",
     "a": "Read books and exercise",
     "d": [
      "Cook and travel",
      "Watch films",
      "Play music"
     ],
     "lines": [
      7,
      8
     ]
    },
    {
     "q": "How is Matt feeling?",
     "a": "Not bad",
     "d": [
      "Great",
      "Terrible",
      "Tired"
     ],
     "lines": [
      0,
      1
     ]
    }
   ]
  },
  {
   "lesson": 10,
   "name": "Conversation",
   "lines": [
    {
     "speaker": "andy",
     "phonetic": "salām, sobh bekhayr, chetor-ee?",
     "script": "سَلام، صُبح بِخِیر، چِطُوری؟",
     "english": "Hello, good morning. How are you?"
    },
    {
     "speaker": "ārezoo",
     "phonetic": "salām, khoob-am, merci, chetor-ee?",
     "script": "سَلام، خوبَم، مِرسی، چِطُوری؟",
     "english": "Hello, I’m well thanks. How are you?"
    },
    {
     "speaker": "andy",
     "phonetic": "khaylee khoob-am, merci. man andy hastam.",
     "script": "خِیلی خوبَم، مِرسی. مَن اَندی هَستَم",
     "english": "I’m very well, thank you. I am Andy."
    },
    {
     "speaker": "ārezoo",
     "phonetic": "esmé man ārezoo hast. eeshoon mādaré man-and.",
     "script": "اِسمِ مَن آرِزو هَست. ایشون مادَرِ مَنَند",
     "english": "My name is Arezoo. This is my mother."
    },
    {
     "speaker": "andy",
     "phonetic": "salām.",
     "script": "سَلام",
     "english": "Hello."
    },
    {
     "speaker": "ārezoo",
     "phonetic": "baché dāree?",
     "script": "بَچِه داری؟",
     "english": "Do you have children?"
    },
    {
     "speaker": "andy",
     "phonetic": "balé, yek pesar dāram, esmesh cyrus hast, va yek dokhtar dāram, esmesh hast seemā.",
     "script": "بَلِه، یِک پِسَر دارَم، اِسمِش سیروس هَست، وَ یِک دُختَر دارَم، اِسمِش هَست سیما",
     "english": "Yes, I have a son; his name is Cyrus, and I have a daughter; her name is Seema."
    },
    {
     "speaker": "ārezoo",
     "phonetic": "ahlé eenjā hastee?",
     "script": "اَهلِ اینجا هَستی؟",
     "english": "Are you from here?"
    },
    {
     "speaker": "andy",
     "phonetic": "na, man az eerān hastam, valee dar pāris zendegee meekonam.",
     "script": "نَه، مَن اَز ایران هَستَم، وَلی دَر پاریس زِندِگی می‌کُنَم",
     "english": "No, I am from Iran, but I live in Paris."
    },
    {
     "speaker": "ārezoo",
     "phonetic": "man va mādaram az eerān hasteem, va dar shirāz zendegee meekoneem.",
     "script": "مَن وَ مادَرَم اَز ایران هَستیم، وَ دَر شیراز زِندِگی می‌کُنیم",
     "english": "My mother and I are from Iran, and we live in Shiraz."
    },
    {
     "speaker": "andy",
     "phonetic": "khob, khoshvakhtam, tā ba’d.",
     "script": "خُب، خوشوَقتَم، تا بَعد",
     "english": "Well, pleased to meet you, until later."
    },
    {
     "speaker": "ārezoo",
     "phonetic": "balé, tā ba’d.",
     "script": "بَلِه، تا بَعد",
     "english": "Yes, until later."
    }
   ],
   "questions": [
    {
     "q": "How many children does Andy have?",
     "a": "Two",
     "d": [
      "One",
      "Three",
      "None"
     ],
     "lines": [
      5,
      6
     ]
    },
    {
     "q": "Where does Andy live?",
     "a": "Paris",
     "d": [
      "Iran",
      "Shiraz",
      "Tehran"
     ],
     "lines": [
      7,
      8
     ]
    },
    {
     "q": "Where is Andy from?",
     "a": "Iran",
     "d": [
      "France",
      "Paris",
      "Mexico"
     ],
     "lines": [
      7,
      8
     ]
    },
    {
     "q": "What is the name of Andy's daughter?",
     "a": "Seema",
     "d": [
      "Arezoo",
      "Donna",
      "Marjan"
     ],
     "lines": [
      5,
      6
     ]
    },
    {
     "q": "Where do Arezoo and her mother live?",
     "a": "Shiraz",
     "d": [
      "Paris",
      "Iran",
      "Tehran"
     ],
     "lines": [
      9
     ]
    }
   ]
  },
  {
   "lesson": 10,
   "name": "Bonus Conversation (there's a lot of new vocabulary in this conversation, so don't worry about learning it all yet!)",
   "lines": [
    {
     "speaker": "dāriush",
     "phonetic": "salām, rooz bekhayr, chetor-ee?",
     "script": "سَلام، روز بِخِیر، چِطُوری؟",
     "english": "Hello, good day. How are you?"
    },
    {
     "speaker": "ānā",
     "phonetic": "salām, khoob-am, merci.",
     "script": "سَلام، خوبَم، مِرسی",
     "english": "Hello, I’m fine, thanks."
    },
    {
     "speaker": "dāriush",
     "phonetic": "esmé tō chee-yé?",
     "script": "اِسمِ تُو چیِه؟",
     "english": "What's your name?"
    },
    {
     "speaker": "ānā",
     "phonetic": "esmé man ānā hast. az mekzeek hastam, az monterrey.",
     "script": "اِسمِ مَن آنا هَست. اَز َمِکزیک هَستَم، اَز مُونتِرِی",
     "english": "My name is Ana. I'm from Mexico, from Monterrey."
    },
    {
     "speaker": "dāriush",
     "phonetic": "valee fārsi sohbat meekonee!",
     "script": "وَلی فارسی صُحبَت می‌کُنی",
     "english": "But you speak Persian!"
    },
    {
     "speaker": "ānā",
     "phonetic": "balé, fārsi baladam.",
     "script": "بَلِه، فارسی بَلَدَم",
     "english": "Yes, I know Persian."
    },
    {
     "speaker": "dāriush",
     "phonetic": "man dāriush hastam. dar āustin zendegee meekonam valee az eerān hastam.",
     "script": "مَن داریوش هَستَم. دَر آستین زِندِگی می‌کُنَم وَلی اَز ایران هَستَم",
     "english": "I'm Dariush. I live in Austin, but I'm from Iran."
    },
    {
     "speaker": "ānā",
     "phonetic": "khāhar barādar dāree?",
     "script": "خواهَر بَرادَر داری؟",
     "english": "Do you have any brothers or sisters?"
    },
    {
     "speaker": "dāriush",
     "phonetic": "balé, yek khāhar dāram va yek barādar dāram. esmé khāharam donnā hast va esmé barādaram daron hast. tō chetor? khāhar barādar dāree?",
     "script": "بَلِه، یِک خواهَر دارَم وَ یِک بَرادَر دارَم. اِسمِ خواهَرَم دانا هَست وَ اِسمِ بَرادَرَم دَرُن هَست. تُو چِطُور؟ خواهَر بَرادَر داری؟",
     "english": "Yes, I have one brother, and I have one sister. My sister's name is Donna, and my brother's name is Daron. What about you? Do you have any brothers or sisters?"
    },
    {
     "speaker": "ānā",
     "phonetic": "balé, dō khāhar, eliānā va eetzel.",
     "script": "بَلِه، دُو خواهَر، اِلیانا وَ ایتزِل",
     "english": "Yes, two sisters, Eliana and Itzel."
    },
    {
     "speaker": "dāriush",
     "phonetic": "shāgerd hastee?",
     "script": "شاگِرد هَستی؟",
     "english": "Are you a student?"
    },
    {
     "speaker": "ānā",
     "phonetic": "balé, dar dāneshgāhé teksās dars meekhoonam, valee dar restoorān ham kār meekonam.",
     "script": "بَلِه، دَر دانِشگاهِ تِکساس دَرس می‌خونَم، وَلی دَر رِستوران هَم کار می‌کُنَم",
     "english": "Yes, I study at the University of Texas, but I also work at a restaurant."
    },
    {
     "speaker": "dāriush",
     "phonetic": "khaylee khoob-é. man ham dar dāneshgāhé teksās shāgerd hastam, valee beekār-am. mooseeghee doost dāree?",
     "script": "خِیلی خوبِه. مَن هَم دَر دانِشگاهِ تِکساس شاگِرد هَستَم، وَلی بیکارَم. موسیقی دوست داری؟",
     "english": "Very nice. I'm also a student at the University of Texas, but I'm unemployed. Do you like music?"
    },
    {
     "speaker": "ānā",
     "phonetic": "balé, mooseeghee doost dāram.",
     "script": "بَلِه، موسیقی دوست دارَم",
     "english": "Yes, I like music."
    },
    {
     "speaker": "dāriush",
     "phonetic": "man ham mooseeghee doost dāram. khob, khoshvakhtam, bé omeedé deedār!",
     "script": "مَن هَم موسیقی دوست دارَم. خُب، خوشوَقتَم، بِه اُمّیدِ دیدار",
     "english": "I like music, too. Well, it was nice to meet you; see you later!"
    },
    {
     "speaker": "ānā",
     "phonetic": "balé, bé hamcheneen!",
     "script": "بَلِه، بِه هَمچِنین",
     "english": "Yes, me, too!"
    }
   ],
   "questions": [
    {
     "q": "Where is Ana from?",
     "a": "Mexico",
     "d": [
      "Iran",
      "The United States",
      "Austin"
     ],
     "lines": [
      2,
      3
     ]
    },
    {
     "q": "How many sisters does Ana have?",
     "a": "Two",
     "d": [
      "One",
      "Three",
      "None"
     ],
     "lines": [
      9
     ]
    },
    {
     "q": "How many sisters does Dariush have?",
     "a": "One",
     "d": [
      "Two",
      "Three",
      "None"
     ],
     "lines": [
      7,
      8
     ]
    },
    {
     "q": "Where does Dariush live?",
     "a": "Austin",
     "d": [
      "Iran",
      "Mexico",
      "Monterrey"
     ],
     "lines": [
      6
     ]
    },
    {
     "q": "Where do Dariush and Ana both study?",
     "a": "The University of Texas",
     "d": [
      "The University of Tehran",
      "A school in Mexico",
      "They are not students"
     ],
     "lines": [
      11,
      12
     ]
    },
    {
     "q": "What do both Dariush and Ana like?",
     "a": "Music",
     "d": [
      "Sports",
      "Cooking",
      "Reading"
     ],
     "lines": [
      13,
      14
     ]
    }
   ]
  }
 ],
 "alphabet": [
  {
   "letter": "ا",
   "name": "alef",
   "sound": "ā: long a, as in \"not\"",
   "rwLesson": 1,
   "family": null,
   "connects": false,
   "note": "Written آ (alef maddé) at the start of a word. Does not connect to the next letter."
  },
  {
   "letter": "و",
   "name": "vāv",
   "sound": "oo: as in \"food\" (also v)",
   "rwLesson": 1,
   "family": null,
   "connects": false,
   "note": "Does not connect to the next letter."
  },
  {
   "letter": "ی",
   "name": "yé",
   "sound": "ee: as in \"see\" (also y)",
   "rwLesson": 1,
   "family": "tooth",
   "connects": true,
   "note": "At the start of a word it looks like ب/پ/ت but with two dots below."
  },
  {
   "letter": "ب",
   "name": "bé",
   "sound": "b: as in \"boy\"",
   "rwLesson": 2,
   "family": "tooth",
   "connects": true,
   "note": "One dot below."
  },
  {
   "letter": "ت",
   "name": "té",
   "sound": "t: as in \"tea\"",
   "rwLesson": 2,
   "family": "tooth",
   "connects": true,
   "note": "Two dots above, same base shape as ب."
  },
  {
   "letter": "پ",
   "name": "pé",
   "sound": "p: as in \"pen\"",
   "rwLesson": 2,
   "family": "tooth",
   "connects": true,
   "note": "Three dots below, same base shape as ب."
  },
  {
   "letter": "د",
   "name": "dāl",
   "sound": "d: as in \"door\"",
   "rwLesson": 2,
   "family": null,
   "connects": false,
   "note": "Does not connect to the next letter."
  },
  {
   "letter": "ن",
   "name": "noon",
   "sound": "n: as in \"nice\"",
   "rwLesson": 3,
   "family": "tooth",
   "connects": true,
   "note": "One dot above; at the start of a word it looks like ب with the dot on top."
  },
  {
   "letter": "ر",
   "name": "ré",
   "sound": "r: rolled r",
   "rwLesson": 3,
   "family": "re",
   "connects": false,
   "note": "Does not connect to the next letter."
  },
  {
   "letter": "ز",
   "name": "zé",
   "sound": "z: as in \"zoo\"",
   "rwLesson": 3,
   "family": "re",
   "connects": false,
   "note": "Same shape as ر plus one dot above. Does not connect to the next letter."
  },
  {
   "letter": "م",
   "name": "meem",
   "sound": "m: as in \"moon\"",
   "rwLesson": 4,
   "family": null,
   "connects": true,
   "note": ""
  },
  {
   "letter": "س",
   "name": "seen",
   "sound": "s: as in \"sun\"",
   "rwLesson": 6,
   "family": "seen",
   "connects": true,
   "note": ""
  },
  {
   "letter": "ش",
   "name": "sheen",
   "sound": "sh: as in \"shah\"",
   "rwLesson": 9,
   "family": "seen",
   "connects": true,
   "note": "Same shape as س plus three dots above."
  },
  {
   "letter": "خ",
   "name": "khé",
   "sound": "kh: the throaty Persian kh",
   "rwLesson": 9,
   "family": null,
   "connects": true,
   "note": ""
  },
  {
   "letter": "گ",
   "name": "gāf",
   "sound": "g: as in \"go\"",
   "rwLesson": 10,
   "family": "kaf",
   "connects": true,
   "note": "Like ک with an extra stroke on top."
  }
 ],
 "readWords": [
  {
   "script": "مَن",
   "phonetic": "man",
   "english": "me / I"
  },
  {
   "script": "بَد",
   "phonetic": "bad",
   "english": "bad"
  },
  {
   "script": "آب",
   "phonetic": "āb",
   "english": "water"
  },
  {
   "script": "نان",
   "phonetic": "nān",
   "english": "bread"
  },
  {
   "script": "دَر",
   "phonetic": "dar",
   "english": "door / in"
  },
  {
   "script": "سَلام",
   "phonetic": "salām",
   "english": "hello"
  },
  {
   "script": "مادَر",
   "phonetic": "mādar",
   "english": "mother"
  },
  {
   "script": "بَرادَر",
   "phonetic": "barādar",
   "english": "brother"
  }
 ],
 "lessons": [
  {
   "lesson": 1,
   "title": "How to Greet People and Ask How They're Doing"
  },
  {
   "lesson": 2,
   "title": "How to Greet People at Different Times of Day, Say Goodbye, and Introduce Yourself"
  },
  {
   "lesson": 3,
   "title": "How to Introduce Where You are From, and Introducing the Different forms of You"
  },
  {
   "lesson": 4,
   "title": "How to Say Where You Live, and Answer Simple Questions"
  },
  {
   "lesson": 5,
   "title": "How to Talk About Your Family, and Introduce Their Names"
  },
  {
   "lesson": 6,
   "title": "How to Talk More About Your Family, and How to Count to Ten"
  },
  {
   "lesson": 7,
   "title": "How to Talk About Your Job and Where You Work"
  },
  {
   "lesson": 8,
   "title": "How to Talk About Your Likes and Dislikes"
  },
  {
   "lesson": 9,
   "title": "How to Use Question Words, More Family Vocabulary, and a Few Filler Words and Phrases"
  },
  {
   "lesson": 10,
   "title": "Review of Unit 1!"
  }
 ],
 "exercises": [
  {
   "id": "ex1",
   "emoji": "🔤",
   "name": "Exercise One",
   "desc": "Translate Persian into English",
   "kicker": "Translate into English",
   "items": [
    {
     "q": "salām, chetor-ee?",
     "a": "Hello, how are you? (informal)"
    },
    {
     "q": "bé omeedé deedār.",
     "a": "Hope to see you."
    },
    {
     "q": "shomā ahlé kojā hasteen?",
     "a": "Where are you from? (formal)"
    },
    {
     "q": "man az espāniā hastam.",
     "a": "I am from Spain."
    },
    {
     "q": "man az āmreekā neestam.",
     "a": "I am not from the United States."
    },
    {
     "q": "kojā zendegee meekonee?",
     "a": "Where do you live?"
    },
    {
     "q": "eeshoon mādaré man hastand.",
     "a": "This is my mother."
    },
    {
     "q": "man sé khāhar dāram.",
     "a": "I have 3 sisters."
    },
    {
     "q": "man dar kārkhooné kār meekonam.",
     "a": "I work in a factory."
    },
    {
     "q": "chekāré hastee?",
     "a": "What do you do? (informal)"
    },
    {
     "q": "man vakeel hastam.",
     "a": "I am a lawyer."
    },
    {
     "q": "kāram-ō doost dāram.",
     "a": "I like my job."
    },
    {
     "q": "ahlé kojā hastee?",
     "a": "Where are you from? (informal)"
    }
   ]
  },
  {
   "id": "ex2",
   "emoji": "✂️",
   "name": "Exercise Two",
   "desc": "Write phrases in reduced form",
   "kicker": "Choose the reduced form",
   "items": [
    {
     "q": "esmé man sārā hast.",
     "a": "esmam sārā-st."
    },
    {
     "q": "esmé man jacob hast.",
     "a": "esmam jacob-é."
    },
    {
     "q": "esmé man matt hast.",
     "a": "esmam matt-é."
    },
    {
     "q": "esmé man sherry hast.",
     "a": "esmam sherry-st."
    }
   ]
  },
  {
   "id": "ex3",
   "emoji": "🔗",
   "name": "Exercise Three",
   "desc": "Match English to Persian",
   "kicker": "Choose the Persian translation",
   "items": [
    {
     "q": "What is your name? (informal)",
     "a": "esmé tō chee-yé?"
    },
    {
     "q": "I am from Paris.",
     "a": "man az pāris hastam."
    },
    {
     "q": "I live in Canada.",
     "a": "man dar kānādā zendegee meekonam."
    },
    {
     "q": "Where do you live? (formal)",
     "a": "kojā zendegee meekoneen?"
    },
    {
     "q": "This is my sister. Her name is Kathy.",
     "a": "een khāharé man-é. esmesh kathy-é."
    },
    {
     "q": "Until tomorrow.",
     "a": "tā fardā."
    },
    {
     "q": "I have a sister and a brother.",
     "a": "man yek khāhar dāram va yek barādar dāram."
    },
    {
     "q": "I work in an office.",
     "a": "man dar edāré kār meekonam."
    },
    {
     "q": "I am an architect.",
     "a": "man me'mār hastam."
    },
    {
     "q": "I like music.",
     "a": "man mooseeghee doost dāram."
    },
    {
     "q": "I like to learn Persian.",
     "a": "doost dāram farsi yād begeeram."
    },
    {
     "q": "Do you like your job? (informal)",
     "a": "kāret-ō doost dāree?"
    },
    {
     "q": "What is your name? (formal)",
     "a": "esmé shomā chee-yé?"
    },
    {
     "q": "Goodnight.",
     "a": "shab bekhayr."
    },
    {
     "q": "I am not bad.",
     "a": "bad neestam."
    }
   ]
  },
  {
   "id": "ex4",
   "emoji": "🔢",
   "name": "Exercise Four",
   "desc": "Numbers in phonetic Persian",
   "kicker": "Write this number in phonetic Persian",
   "items": [
    {
     "q": "1",
     "a": "yek"
    },
    {
     "q": "2",
     "a": "dō"
    },
    {
     "q": "3",
     "a": "sé"
    },
    {
     "q": "4",
     "a": "chahār"
    },
    {
     "q": "5",
     "a": "panj"
    },
    {
     "q": "6",
     "a": "sheesh"
    },
    {
     "q": "7",
     "a": "haft"
    },
    {
     "q": "8",
     "a": "hasht"
    },
    {
     "q": "9",
     "a": "noh"
    },
    {
     "q": "10",
     "a": "dah"
    }
   ]
  },
  {
   "id": "ex5",
   "emoji": "📝",
   "name": "Exercise Five",
   "desc": "Translate the sentences into Persian",
   "kicker": "Choose the Persian",
   "items": [
    {
     "q": "I have 3 sisters and 2 brothers.",
     "a": "sé khāhar va dō barādar dāram."
    },
    {
     "q": "I have 4 fathers.",
     "a": "chahār pedar dāram."
    },
    {
     "q": "I have 8 sons.",
     "a": "hasht pesar dāram."
    },
    {
     "q": "I have 1 mother.",
     "a": "yek mādar dāram."
    },
    {
     "q": "I have a wife.",
     "a": "yé zan dāram."
    },
    {
     "q": "I have 2 husbands.",
     "a": "dō shohar dāram."
    },
    {
     "q": "I have 6 daughters.",
     "a": "sheesh dokhtar dāram."
    }
   ]
  }
 ]
};
